Repository JosephMezza/SOEN341, pull requests merged in 2021-02, with the labels that each got.

#6 Readme edits
  README.md
Labels: documentation

#7 Create basic flask template
  app.py
Labels: enhancement

#31 Created the database
  .DS_Store
  database.py
Labels: back-end

#36 Front end design of pages
  .vscode/settings.json
  Index.html
  app.py
  static/images/addimage.png
  static/images/img1.jpg
  static/images/img2.jpg
  static/images/img3.jpg
  static/images/img4.jpg
  static/images/img5.jpg
  static/images/img6.jpg
  static/images/img7.jpg
  static/images/img8.jpg
  static/images/img9.jpg
  static/images/key.png
  static/images/polaroid.jpg
  static/images/user.png
  static/login.css
  static/signup.css
  static/stylesheet.css
  templates/base.html
  templates/login.html
  templates/main.html
  templates/post.html
  templates/signup.html
Labels: Front-end

#38 Organization
  .gitignore
  .vscode/settings.json
  app.py
  requirements.txt
Labels: Low, documentation
