Repository JosephMezza/SOEN341, pull requests merged in 2021-03, with the labels that each got.

#65 Added Caption Functionality and Improved HTML for Upload Page
  app.py
  data/posts.csv
  data/userImages.csv
  forms.py
  posts.py
  static/images/PatrickChamp.png
  static/images/polaroidWall.jpg
  static/posts.css
  templates/base.html
  templates/caption.html
  templates/upload-image.html
Labels: Front-end, back-end

#73 Transposed to encrypted passwords
  .vscode/settings.json
  app.py
  data/users.csv
Labels: back-end

#78 Password reset
  __pycache__/follower.cpython-39.pyc
  __pycache__/forms.cpython-39.pyc
  app.py
  emailsend.py
  forms.py
  static/images/Capture.PNG
  static/images/Rotating_earth_(large).gif
  templates/forgotPassword.html
  templates/login.html
  templates/resetPassword.html
Labels: back-end, help wanted, medium
